### PR TITLE
activate extra and major modes first

### PR DESCRIPTION
**Pull request by npostavs**
```
* yasnippet.el (yas--modes-to-activate): Reverse result, so that parents
  of yas--extra-modes and major are later in the list.
* yasnippet-tests.el (loading-with-cyclic-parenthood)
(extra-modes-parenthood): Test it.
```

---

This should take care of the particular case that [@uu1101 brought up](https://github.com/capitaomorte/yasnippet/issues/619#issuecomment-149127150), though the ordering between parent modes is still fairly arbitrary. Which is to say, [case 3](https://github.com/capitaomorte/yasnippet/issues/619#issuecomment-149303644) may not be respected, but it's kind of annoying to implement and test for, and it seems unlikely to come up in practice, so I'm leaning towards sticking with this 90% solution.

### CODE REVIEW

**Comment by capitaomorte** [comment]
> Sticking with this 90% solution.

Fine by me.  Perhaps prefix the commit message with a "Fixes #619"?

**Comment by npostavs** [comment]
> Perhaps prefix the commit message with a "Fixes #619"?

Well it doesn't fix #619 as such, perhaps "fixes the fix of #619" ;)

**Comment by capitaomorte** [comment]
> Well it doesn't fix #619 as such, perhaps "fixes the fix of #619" ;)
Right, I usually don't go for that kind of accuracy :-), it's nice just to have a reference.

**Comment by uu1101** [comment]
Thank you very much!

**Pull request closed without merging**
