### PR TITLE
Experimenting with Emacs install for Travis CI

### PR DESCRIPTION
**Pull request by npostavs**
```
* .travis.yml: get Emacs from https://github.com/npostavs/emacs-travis/releases
```

### CODE REVIEW

**Comment by capitaomorte** [comment]
Nice! Gonna use this for my other projects! Should speed up testing I guess.

**Comment by npostavs** [comment]
> Gonna use this for my other projects! Should speed up testing I guess.

I can't promise stable URLs or untarring commands yet, but yeah it should be way faster for testing Emacs versions different from what's already installed by default (23.something, I think).

**Comment by capitaomorte** [comment]
> I can't promise stable URLs 

Github should have you covered, right?

> or untarring commands yet,

What do you mean? Untarring commands that allow installing somewhere else besides `/tmp`?

**Comment by syohex** [comment]
How about [EVM](https://github.com/rejeep/evm) ? Many projects uses EVM like spacemacs, smartparens, markdown-mode etc. Tests are fast by `sudo: false`.

Test on travis-ci works on some Emacs versions with following `.travis.yml`. Result is here(https://travis-ci.org/syohex/yasnippet).

```yaml
language: generic
sudo: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
env:
  - EVM_EMACS=emacs-24.3-travis
  - EVM_EMACS=emacs-24.4-travis
  - EVM_EMACS=emacs-24.5-travis
script:
  - emacs --version
  - rake compile; rake tests
```

**Comment by npostavs** [comment]
> Github should have you covered, right?

I meant deciding on file naming and such.

> What do you mean? Untarring commands that allow installing somewhere else besides /tmp?

e.g. I just changed it to use `--absolute-names`.

> How about EVM ? Many projects uses EVM like spacemacs, smartparens, markdown-mode etc. Tests are fast by sudo: false.

Last time I looked at it, there was a long delay before 24.5 was released, and as far as I know, a version 25 snapshot is not available as binary. The main benefit of getting the binaries from https://github.com/npostavs/emacs-travis/releases is that they are uploaded from a travis script so it will be easy to have a reasonably up to date Emacs 25 and master versions. Perhaps we can integrate this technique with EVM so it can provide more recent binaries.

**Pull request merged**
