### PR TITLE
Feature/custom yas backport obsolete alias

### PR DESCRIPTION
**Pull request by npostavs**
extend/replace/ close #696.

### CODE REVIEW

**Comment by zonuexe** [comment]
@npostavs said: https://github.com/capitaomorte/yasnippet/pull/696#issuecomment-219699793

> Do you think it's worth adding some code so that the aliases can be removed/added after loading as well?

No, I do not think there is a chance to revive again the old prefixed symbols.

**Comment by npostavs** [comment]
> No, I do not think there is a chance to revive again the old prefixed symbols.

I meant changing the code so that we wouldn't have this wrinkle that `yas-alias-to-yas/prefix-p` "must be set to nil before loading yasnippet to take effect".

I've added this in the docstring now. I've also made `yas/snippet-dir` also be affected by the `yas-alias-to-yas/prefix-p` option.

**Comment by zonuexe** [comment]
👍

**Comment by capitaomorte** [comment]
@npostavs, do we have any idea of how much havoc would be wreaked if this was removed altogether in the next version? Or perhaps the new option could be set to nil by default: I wouldn't oppose it, I mean, it's been deprecated for some time now...

**Comment by npostavs** [comment]
I've seen elisp fragments with `yas/` floating around fairly recently and [a search][s] turns up several examples. I want to wait at least a couple more versions before removing it, especially since it turns out `yas/snippet-dir` wasn't actually marked obsolete up until now.

[s]: https://github.com/search?l=emacs-lisp&o=desc&q=yas&ref=searchresults&s=&type=Code&utf8=%E2%9C%93

**Comment by capitaomorte** [comment]
OK. My take on this is that one thing is removing it completely, another is defaulting the new option to `nil`. You should probably do the latter sooner than the former. The fact that `yas/snippet-dirs` (not `yas/snippet-dir`, right?) wasn't marked obsolete is a technical detail (unless there was official documentation inadvertently referring to it). It isn't really important imo, since the `yas/...` aliases are de facto obsoleted for some years (not versions though).

**Comment by npostavs** [comment]
> My take on this is that one thing is removing it completely, another is defaulting the new option to nil. You should probably do the latter sooner than the former.

Agreed.

> The fact that `yas/snippet-dirs` (not `yas/snippet-dir`, right?) wasn't marked obsolete is a technical detail

Oops, no, I meant `yas/root-directory`, wasn't marked obsolete. And although the commentary mentions that it is obsolete, it was easier to be unaware of it since no warning message would be printed when using it.

**Pull request merged**
