### PR TITLE
Fix #597; allow visiting compiled snippets

### LINKED ISSUE #597: yas-visit-snippet-file when snippets have been compiled
I guess this is more of a question. When I have compiled my snippets (thus creating `.yas-compiled-snippets.el` files), `yas-visit-snippet-file` doesn't take me to the original snippet files, but instead open up a kind of inspect-only buffer which can't be saved with `yas-load-snippet-buffer-and-close` (first, it can't guess the file; second, the compiled snippet comes with parts of my comments stripped). Is there a workaround in such a case? Or do I have to manually navigate to the snippet file, which is simply far less efficient?

### PR DESCRIPTION
**Pull request by npostavs**

### CODE REVIEW

**Comment by npostavs** [comment]
@capitaomorte: I was just reminded looking at this again, shouldn't it be `file-name-NONdirectory` or `file-name-base` instead of `file-name-directory` for the fallback `name` value?

```elisp
                 (name (or xname
                           (and load-file (file-name-directory load-file))
                           (and save-file (file-name-directory save-file))
                           key))
```

```elisp
;; original:
(let* (...
         (name (or (third snippet)
                   (and file
                        (file-name-directory file))))
         ...)
    ...
    (setf (yas--template-name template)       (or name key)))

```

**Comment by capitaomorte** [comment]
It does seem so, butI can't tell yet. This is old code, that should be
working
or we would've heard from issues, especially with old directiveless
snippets.
Perhaps people aren't using those anymore.

Anyway, I'm on holiday and and can't really look into it or test. Does a
nameless
snippet calculate its name correctly before/after this change?





On Tue, Sep 8, 2015 at 10:48 PM, Noam Postavsky <notifications@github.com>
wrote:

> @capitaomorte <https://github.com/capitaomorte>: I was just reminded
> looking at this again, shouldn't it be file-name-NONdirectory or
> file-name-base instead of file-name-directory for the fallback name value?
>
>                  (name (or xname
>                            (and load-file (file-name-directory load-file))
>                            (and save-file (file-name-directory save-file))
>                            key))
>
> ;; original:
> (let* (...
>          (name (or (third snippet)
>                    (and file
>                         (file-name-directory file))))
>          ...)
>     ...
>     (setf (yas--template-name template)       (or name key)))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/capitaomorte/yasnippet/pull/603#issuecomment-138713857>
> .
>



-- 
João Távora

**Comment by npostavs** [comment]
> should be working or we would've heard from issues, especially with old directiveless snippets.

Yeah, that's why I decided not to change it.

**Comment by npostavs** [comment]
> Does a nameless snippet calculate its name correctly before/after this change?

Ah, yes it's because `yas--parse-template` does the right thing:
```elisp
  (let* (...
         (name (and file
                    (file-name-nondirectory file)))
...
    (unless (or key binding)
      (setq key (and file (file-name-nondirectory file))))
```
So `yas--define-snippet-{1,2}` always get a non-nil `name`.

**Pull request merged**
